### PR TITLE
Fix keybord lock

### PR DESCRIPTION
**Pull request by kitune-san**
Bug fixes for KF8259 have been made. This will no longer cause an interrupt deadlock in 8088bios.

### CODE REVIEW

**Comment by spark2k06** [comment]
Tested. The overall performance of the core is similar, the IBM 5160 BIOS error 101 still occurs... but the downside is that the Interrupt Level 0 error in the SuperSoft test ROM has returned with this patch.

**Comment by spark2k06** [comment]
On the other hand, the one that causes the problems with Interrupt Level 0 in the SuperSoft test is the one called "Fixed 8259 interrupt request logic", the other commit also passes the tests.

I see that you are focusing on the performance of the ROM that I have left set by default, that of a clone of 8088 PCXT of Sergey Kiselev, I keep it because it is Open Source, but it may have its bugs or incompatibilities with this core. In fact, one thing I have noticed with this BIOS is that the execution of the DIR command has a quite slow scroll, compared for example with the consolidated Juko ST BIOS, which is the one I am starting to use for all the tests.

In fact, this BIOS doesn't have any problems with the keyboard, like Sergey's 8088 ROM does. Besides, with the last changes you made, it doesn't show any keyboard error, and the original IBM 5160 BIOS doesn't show 301 code either, so, in this sense I think we could consider the keyboard problem solved, and I could accept the commit "Fixed interrupt_to_cpu to be set back to LOW when interrupt request disappears" if you consider it convenient.

I assume Sergey's 8088 BIOS has some "bugs" that might require future revision to make it compatible with this core.

**Comment by spark2k06** [comment]
In summary, the ROMs we should use for core development are:

- SuperSoft tests
- Ruud tests
- IBM 5150/5160 BIOS
- Juko ST BIOS

And finally, in the future, adapt and improve the Sergey's 8088 BIOS, since it is OpenSource and is the current candidate to be kept on GitHub.

**Comment by kitune-san** [comment]
Sorry for the late reply.
Ok. I will review it again.
I close this pull request.

**Comment by spark2k06** [comment]
No problem, thank you for your contributions!

**Pull request closed without merging**
